### ISSUE TITLE
Memory Hungry

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [latex-lsp/texlab-vscode#39] opened 2019-05-07 12:41 UTC
When I tried it, even when the extension was disabled, it spammed a java program (`server/texlab.jar` I think) that took more than 4g memories. And every restart/reload it spammed more processes. After a few seconds or minutes the old process will eventually release its memory but in the mean time the high memory usage spike is a big problem. 

Is that a common behavior? Can you guys fix it?

**Comment by efoerster** [comment] 2019-05-10 06:11
Thanks for the report. On my computer, the java process uses ~400MB, which is indeed too high. We are currently rewriting the language server in Rust, which will improve this greatly. 
Do you have a workspace with real big files or deep nested directories opened?

The reload bug seems to be caused by the LSP library that we use. But I will do further research.

**Comment by Turgon-Aran-Gondolin** [comment] 2019-05-10 10:05
Yes I do have a fairly large workspace opened. While that being true, memory usage of several hundred MBs is OK by me.

**Comment by efoerster** [comment] 2019-07-04 09:03
This should be fixed now with the new version. The server uses now ~20MB instead of 400 on the same workspace.

**Closed by efoerster** 2019-07-04 09:03 UTC
